replicaCount: 1

image:
  repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/user
  tag: 9f0cc45
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  host: user.hardikdevportal.duckdns.org