appName: shop
namespace: shop

frontend:
  enabled: true
  replicas: 1
  image:
    repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/shop-frontend
    tag: 871d8bd
    pullPolicy: IfNotPresent
  port: 3000
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  
backend:
  enabled: true
  replicas: 1
  image:
    repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/shop-backend
    tag: 871d8bd
    pullPolicy: IfNotPresent
  port: 8000
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
ingress:
  host: shop.hardikdevportal.duckdns.org