apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: nginx-test-secrets
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore

  target:
    name: nginx-test-app-secrets
    creationPolicy: Owner

  data:
    - secretKey: db-password
      remoteRef:
        key: /devportal/dev/db-password

    - secretKey: api-key
      remoteRef:
        key: /devportal/dev/api-key