{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: frontend
    managed-by: devportal
spec:
  replicas: 1
  selectors:
    matchlabels:
      app: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: frontend
    spec:
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{.Values.frontend.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.frontend.port}}
          resources:
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
{{- end }}
