apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    managed-by: devportal
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 80
          {{- end }}
          {{- if .Values.frontend.enabled }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80
          {{- end }}

