replicaCount: 1

image:
  repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/devportal-nginx-test
  tag: 7d4d154fe00db7fe29d42f62fb4a6a6f892c4575
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress: 
  host: hardikdevportal.duckdns.org