replicaCount: 1

image:
  repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/devportal-nginx-test
  tag: 09f3035c350b4c6fb0e8593c2c63ea368a73ea84
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress: 
  host: hardikdevportal.duckdns.org