replicaCount: 1

image:
  repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/devportal-nginx-test
  tag: 3d7314f7212347b67c8622633d518c9937db5d7f
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress: 
  host: hardikdevportal.duckdns.org