replicaCount: 1

image:
  repository: 746486152802.dkr.ecr.ap-south-1.amazonaws.com/devportal-nginx-test
  tag: c55134bcd4f2a3940beaeaeeb5ed3f6c1299f89d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress: 
  host: hardikdevportal.duckdns.org